### ISSUE TITLE
프로젝트의 진행보다, 같이 개발하는 방법론을 찾아보기.

### ISSUE THREAD

**Issue by khw7096** [coldmine/lv#10]
프로젝트의 진행보다, 같이 개발하는 방법론을 찾아보기.

**Comment by redbean** [comment]
프로젝트의 진행에 대한 이야기로 포인트를 잡는다고 생각되긴 하지만 방법론에 있어 okr을 적용해서 개발하는 것도 나쁘지는 않다고 요즘 생각합니다.
팀의 목표와 개인의 목표를 설정하고 특정시점에서 리뷰하면 분명 좋은 방향으로 갈수 있다고 생각해요

현재 지금 진행되고 있는 프로젝트는 okr리스트와 스케쥴표를 만들고 공유해서 진행하려 힘쓰고 있습니다. 결과는 나중에 개인적으로 진행할 포스트모템에서 많은 내용이 나올꺼 같네요.

**Comment by khw7096** [comment]
이건 취미라서 회사프로젝트처럼 하고 싶지 않아요.ㅋ 개발론보다는 리뷰와 토론?
그리고 누가 무엇을 맡아서 어떻게 협업이 가능할지 고민하는 정도가 포커스인데.. 다른 사람들은 어떻게 생각해요?

**Comment by khw7096** [comment]
토론이 시작되어서 다시 리오픈했어요

**Comment by kybin** [comment]
제 생각엔..

하고 싶은 부분을 찾는다. 한다.

**Comment by redbean** [comment]
시작 시 지금처럼 많은 이슈가 공유되면 토론은 활성화 될것 같네요..

**Comment by kybin** [comment]
네. 이 방법은 저희도 처음 써보는건데 해보면서 느끼는건.. 엄청 좋아요.

**Comment by redbean** [comment]
좀 더 나가자면
중간 합류자가 이슈를 어떻게 따라오느냐도 하나의 고민이 될수 있겠다는 생각이 드네요

**Comment by redbean** [comment]
정리해서
1. 시작 시 목적과 이슈가 업데이트 된다 (개발자가 같은 목적과 방법을 공유한다)
2. 중간 합류자가 합류 시 진행사항을 최대한 빠르게 캐치하는 방법이 필요하지 않을까?

네요

**Comment by kybin** [comment]
사실 그 부분은 거의 답이 없죠. 원래 중간에 합류를 하면 어려운 법이니까요.
우리 같은 경우는 서로 만날수 있으니 만나서 얘기를 해주는것도 방법일것 같아요.
좋은 README파일도 필요하고.

**Comment by khw7096** [comment]
저도 이 부분은 수많은 참고서들이 있지만, 우리가 직접 몸으로 부딪혀봐야  그러한 글들을 읽었을 때 몸으로 와닿을것 같아요. 결국 실질적인 방법은.

명확한 Readme를 작성한다.!
주석을 잘 단다.
서로에게 설명을 잘해준다.

**Comment by khw7096** [comment]
테스크가 아니라서 닫음.
