### ISSUE TITLE
맥에서 xquarts는 왜 필요한거에요?

### ISSUE THREAD

**Issue by kybin** [coldmine/lv#21]

**Comment by khw7096** [comment]
그게 없으면 샤이니가 실행안됨.

**Comment by kybin** [comment]
xquartz가 뭐에요?

**Comment by khw7096** [comment]
xquartz는 맥에서 x11을 맥에서 표시해주는 윈도우시스템

**Comment by khw7096** [comment]
결론 : 없어도 실행이 되네요.
Xquartz가 이미 깔려있으면 Xquartz로 실행되요.
용빈씨가 집에서 실행했을 때 매번 Xquartz로 실행되고 있어서.. 설마했는데..
그럼 코드중에 cocoa drv는 모지.. 라는 생각에 언인스톨 해봤어요.
삭제했는데.. 실행되네요.ㅋ

**Comment by kybin** [comment]
오케이. 이해했어요.
