### ISSUE TITLE
키보드 숏컷

### ISSUE THREAD

**Issue by kybin** [coldmine/lv#27]

**Comment by khw7096** [comment]
스페이스, 엔터 : 재생, 정지
화살표 : 1프레임씩 넘김.
<,> : 1초씩 넘김.
[,] : 이전,다음 아이템으로 넘김.

다른사람들의 의견은?

**Comment by kybin** [comment]
스페이스로 재생/정지
5초 앞/뒤 : 화살표
프레임: <>
이전/다음 아이템: []

저는 약간 동영상 재생에 더 초점을 맞추고 싶네요~

**Comment by redbean** [comment]
스페이스 : 재생, 정지
화살표 : 1프레임씩 넘김
shift + 화살표  : 5초씩 넘김.
ctrl + 화살표  : 이전,다음 아이템으로 넘김.
i,o 또는 [, ] : 인아웃점

조합으로 움직이게 되면 키를 누르기 위해 손가락을 많이 움직일 필요가 없다고 생각하네요.

**Comment by redbean** [comment]
https://sourceforge.net/projects/djv/?source=typ_redirect
오랫만에 DJV를 영접했네요. 

djv 키보드 숏컷(플레이) 공유 합니다. - for reference

J, K, L : 뒤로 재생, 정지, 앞으로 재생
[, ] : 1프레임씩 이동
shift + [, ] : 10 프레임씩 이동
ctrl + [, ] : 100 프레임씩 이동
i, o : 인아웃 정의
shift + i, o : 인아웃 해제

**Comment by kybin** [comment]
\- , = : 소리 크기 높이기/낮추기

**Comment by kybin** [comment]
f, 엔터: 전체화면

**Comment by kybin** [comment]
일단 기본 키는 잡음. 나중에 추가할일이 생기면 따로 이슈 생성.
