### ISSUE TITLE
재생/정지 메모리 누수

### ISSUE THREAD

**Issue by kybin** [coldmine/lv#28]
66c9704771ef6d4af89b4b8eb8bea3f5cb03474a 로 기능을 구현했는데, 메모리 누수와 느려짐이 있네요.

어떻게 해야 할지 몰라서 일단 올렸어요. 보고 혹시 뭐가 문제인지 알것같으면 알려줘요.

**Comment by kybin** [comment]
의심가는 것 두가지
1. screen.Window는 screen.EventDeque인터페이스를 만족하는데 이 큐가 계속 늘어나고 있는것은 아닐까. 하지만 그걸 체크해볼 방법을 모르겠어요.
2. 메인 select 루프에서 paint.Event가 발생할 때마다 Texture와 Buffer를 생성하는데 이게 쌓여서 그렇게 되는건 아닐까. 그런데 원래 for문이 새로 돌때마다 이전 Texture와 Buffer를 지워야 되는거 아닌가요? 

머리속이 혼란스럽네요.

**Comment by khw7096** [comment]
![checkmem](https://cloud.githubusercontent.com/assets/1149996/17834978/23800e0c-6793-11e6-9977-57a7f04888b6.jpg)

확실히 1분 넘게 실행해보니 메모리는 꾸준히 올라가네요..

**Comment by irenebaek** [comment]
고로 .. ?

2016년 8월 21일 일요일, hanwoong kimnotifications@github.com님이 작성한 메시지:

**Comment by khw7096** [comment]
1번보다는 2번을 체크해보는게 더 쉬워보이니깐. 2번을 먼저 해봅시당.

**Comment by khw7096** [comment]
고로로.. ??

**Comment by kybin** [comment]
고로케?

**Comment by khw7096** [comment]
카페에서 수다나 합시다. 만날까용?

**Comment by kybin** [comment]
ㅇㅋ!

**Comment by kybin** [comment]
오. 함수로 잘 정리한 덕분인지 메모리 누수가 사라졌네요.
이유를 알았다면 더 좋았겠지만 일단 만족!
