### ISSUE TITLE
플레이바.

### ISSUE THREAD

**Issue by kybin** [coldmine/lv#33]
간단한 플레이바를 추가하자.

부른 프레임: 초록색
현재 프레임: 노란색
이 외: 회색

**Comment by kybin** [comment]
풀리퀘스트 요청중.

초록색으로 부른 프레임 표현하는건 아직 되지 않음.

**Comment by irenebaek** [comment]
앗 !

2016년 8월 28일 일요일, kim yongbinnotifications@github.com님이 작성한 메시지:

**Comment by kybin** [comment]
앗!은 뭔가요~ ㅋㅋㅋ

**Comment by irenebaek** [comment]
이미 머지를 !

2016년 8월 28일 일요일, kim yongbinnotifications@github.com님이 작성한 메시지:

**Comment by kybin** [comment]
머지 안됐어요, 이리로!
https://github.com/coldmine/lv/pull/36
