### ISSUE TITLE
상대경로로 arg 입력하면 에러남.

### ISSUE THREAD

**Issue by khw7096** [coldmine/lv#49]
$ lv sample/colorbar.png 
panic: runtime error: integer divide by zero

goroutine 6 [running]:
panic(0x41178a0, 0xc4200120a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.playFramer(0x0, 0x4038000000000000, 0x0, 0x41e7360, 0xc420078000, 0xc4200b0300)
    /Users/kimhanwoong/go/src/github.com/coldmine/lv/lv.go:308 +0x588
created by main.main.func1
    /Users/kimhanwoong/go/src/github.com/coldmine/lv/lv.go:90 +0x270

**Comment by kybin** [comment]
https://github.com/coldmine/lv/issues/47 참고요
상대경로 문제가 아니라 한프레임만 받으면 그렇게 돼요
