### ISSUE TITLE
맥에서 단축키를 눌렀을 때 작동되지 않아요. 흑흑.. 어떡하죠? 흑.

### ISSUE THREAD

**Issue by khw7096** [coldmine/lv#62]
맥에서 단축키를 눌렀을 때 작동되지 않아요. 흑흑.. 어떡하죠? 흑.

**Comment by irenebaek** [comment]
망했컴 !

2016년 10월 8일 토요일, hanwoong kimnotifications@github.com님이 작성한 메시지:

**Comment by khw7096** [comment]
일요일!@@@

**Comment by kybin** [comment]
미안팽!
